### ISSUE TITLE
X, Z = model.sample(500) is not working

### ISSUE THREAD

**Issue by yaaaang** [hmmlearn/hmmlearn#235]
I was trying the sample provided from the code and when it comes to this line:
X, Z = model.sample(500)
The code breaks and a lot of errors appears, repeatedly: 
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/deprecation.py:75: DeprecationWarning: Function sample_gaussian is deprecated; The function sample_gaussian is deprecated in 0.18 and will be removed in 0.20. Use numpy.random.multivariate_normal instead.
  warnings.warn(msg, category=DeprecationWarning)

Someone could tell me how to fix this problem?

PS I am using Python 3.6

**Comment by cfdgcfdg** [comment]
reference to https://github.com/hmmlearn/hmmlearn/pull/213
you should use the newest edition of hmmlearn. The problem has been fixed.

**Comment by necrodancer** [comment]
I have the same issue.
Even though I installed newest version of hmmlearn(0.2.0), the error is still raised.
My environment is anaconda, python 2.7, scikit-learn==0.19.1.

I already read [here](https://github.com/scikit-learn/scikit-learn/issues/10846) and [here](https://github.com/hmmlearn/hmmlearn/pull/213).
But I cannot solve the problem.

Could someone tell me how I fix the problem?
