### ISSUE TITLE
Cannot install hmmlearn on M1 Mac

### ISSUE THREAD

**Issue by saveli** [hmmlearn/hmmlearn#514]
## I am reporting a bug

Cannot install `hmmlearn` on M1 mac. `pip`'s recommendation to use `pip install --use-pep517` does only remove the warning, but still fails to install.

### Version info

```
python -V
Python 3.10.9
```

```
/usr/bin/clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Stack trace

```
pip install hmmlearn
Collecting hmmlearn
  Using cached hmmlearn-0.2.8.tar.gz (61 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy>=1.10
  Using cached numpy-1.24.2-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
Collecting scikit-learn>=0.16
  Using cached scikit_learn-1.2.2-cp310-cp310-macosx_12_0_arm64.whl (8.5 MB)
Collecting scipy>=0.19
  Using cached scipy-1.10.1-cp310-cp310-macosx_12_0_arm64.whl (28.8 MB)
Collecting joblib>=1.1.1
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: hmmlearn
  Building wheel for hmmlearn (setup.py): started
  Building wheel for hmmlearn (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      /opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.10/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.10/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-310
      creating build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/_version.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/utils.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/stats.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/base.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/_utils.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      creating build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_multinomial_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_utils.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/conftest.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_gmm_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_gmm_hmm_multisequence.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_poisson_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_gmm_hmm_new.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_gaussian_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_base.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_categorical_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      running build_ext
      building 'hmmlearn._hmmc' extension
      creating build/temp.macosx-11.0-arm64-cpython-310
      creating build/temp.macosx-11.0-arm64-cpython-310/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/myenv/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/myenv/include -arch arm64 -I/private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include -I/opt/homebrew/Caskroom/miniforge/base/envs/myenv/include/python3.10 -c src/_hmmc.cpp -o build/temp.macosx-11.0-arm64-cpython-310/src/_hmmc.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++11 -mmacosx-version-min=10.9
      src/_hmmc.cpp:35:34: warning: braces around scalar initializer [-Wbraced-scalar-init]
        auto log = py::array_t<double>{{n}};
                                       ^~~
      src/_hmmc.cpp:63:39: warning: braces around scalar initializer [-Wbraced-scalar-init]
        auto scaling_ = py::array_t<double>{{ns}};
                                            ^~~~
      src/_hmmc.cpp:66:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:120:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:154:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:188:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:222:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:258:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:289:47: warning: braces around scalar initializer [-Wbraced-scalar-init]
        auto state_sequence_ = py::array_t<ssize_t>{{ns}};
                                                    ^~~~
      src/_hmmc.cpp:293:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      3 warnings and 7 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn
Failed to build hmmlearn
Installing collected packages: threadpoolctl, numpy, joblib, scipy, scikit-learn, hmmlearn
  Running setup.py install for hmmlearn: started
  Running setup.py install for hmmlearn: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for hmmlearn did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      /opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.10/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      /opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.10/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running install
      /opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-310
      creating build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/_version.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/utils.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/stats.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/base.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/_utils.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      copying lib/hmmlearn/hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn
      creating build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_multinomial_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_utils.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/conftest.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_gmm_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_gmm_hmm_multisequence.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_poisson_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_gmm_hmm_new.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_gaussian_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_base.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      copying lib/hmmlearn/tests/test_categorical_hmm.py -> build/lib.macosx-11.0-arm64-cpython-310/hmmlearn/tests
      running build_ext
      building 'hmmlearn._hmmc' extension
      creating build/temp.macosx-11.0-arm64-cpython-310
      creating build/temp.macosx-11.0-arm64-cpython-310/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/myenv/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/myenv/include -arch arm64 -I/private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include -I/opt/homebrew/Caskroom/miniforge/base/envs/myenv/include/python3.10 -c src/_hmmc.cpp -o build/temp.macosx-11.0-arm64-cpython-310/src/_hmmc.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++11 -mmacosx-version-min=10.9
      src/_hmmc.cpp:35:34: warning: braces around scalar initializer [-Wbraced-scalar-init]
        auto log = py::array_t<double>{{n}};
                                       ^~~
      src/_hmmc.cpp:63:39: warning: braces around scalar initializer [-Wbraced-scalar-init]
        auto scaling_ = py::array_t<double>{{ns}};
                                            ^~~~
      src/_hmmc.cpp:66:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:120:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:154:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:188:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:222:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:258:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      src/_hmmc.cpp:289:47: warning: braces around scalar initializer [-Wbraced-scalar-init]
        auto state_sequence_ = py::array_t<ssize_t>{{ns}};
                                                    ^~~~
      src/_hmmc.cpp:293:8: error: call to deleted constructor of 'pybind11::gil_scoped_release'
        auto nogil = py::gil_scoped_release{};
             ^       ~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/yj/x6vlk00x6671tsryc_qlk24h0000gn/T/pip-install-zvq1lm35/hmmlearn_9444c1f141b14ccbbcd900e7ebff7402/.eggs/pybind11-2.10.4-py3.10.egg/pybind11/include/pybind11/gil.h:155:5: note: 'gil_scoped_release' has been explicitly marked deleted here
          gil_scoped_release(const gil_scoped_release &) = delete;
          ^
      3 warnings and 7 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> hmmlearn
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by anntzer** [comment]
This is fixed as of master by #512.

**Comment by saveli** [comment]
It is not fixed, since installing with `pip install git+...` adds hash+distance as version, checkout and local install results in `0+unknown` as version. Any other package with hmmlearn as requirement will therefore use the old unbuildable `hmmlearn-0.2.8` from PyPi, uninstall beforhand manually installed `hmmlearn-master` and run into build errors.

**Comment by vsmaxim** [comment]
I can confirm that it works on M1 as of latest master, also, if you want to use different version for subdependencies, consider using `poetry` or `pipenv` instead of pip. Having this line in `[tool.poetry.dependencies]` does the job for me:
```toml
[tool.poetry.dependencies]
hmmlearn = {git = "https://github.com/hmmlearn/hmmlearn.git"}
```

**Comment by zia1138** [comment]
Curious if a new release will be out soon. Because of the hash mismatch, hmmlearn is reinstalled when it is a dependency in another pypi package even if you have the github version installed as observed by @saveli. 
Thanks!

**Comment by anntzer** [comment]
> I guess the real issue here is to fix CI to provide M1-compatible wheels, though.

This should be done on master now, via a switch to cibuildwheel.

**Comment by anntzer** [comment]
0.3.0 has been released on PyPI.
