### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by genliu777** [hmmlearn/hmmlearn#87]
my OS is win7 x64 .  visual studio 2015, also visual studio 2013, and python 3.5 x64(by anaconda) are set up. 
hmmlearn is set up successfully. and validated by the code:
        >>>import hmmlearn
        >>> hmmlearn.__version__
and the output is '0.2.0' which is last version of hmmlearn.
but, if i put the code like the following,
        >>>from hmmlearn import hmm
i get the error as the following,

C:\Anaconda3_64\python.exe E:/pycharm/plot_hmm_stock_analysis/hmm_stock_analysis.py
Traceback (most recent call last):
  File "E:/pycharm/plot_hmm_stock_analysis/hmm_stock_analysis.py", line 17, in <module>
    from hmmlearn import hmm
  File "C:\Anaconda3_64\lib\site-packages\hmmlearn-0.2.0-py3.5-win-amd64.egg\hmmlearn\hmm.py", line 14, in <module>
    from sklearn import cluster
  File "C:\Anaconda3_64\lib\site-packages\sklearn\__init__.py", line 57, in <module>
    from .base import clone
  File "C:\Anaconda3_64\lib\site-packages\sklearn\base.py", line 11, in <module>
    from .utils.fixes import signature
  File "C:\Anaconda3_64\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "C:\Anaconda3_64\lib\site-packages\sklearn\utils\validation.py", line 16, in <module>
    from ..utils.fixes import signature
  File "C:\Anaconda3_64\lib\site-packages\sklearn\utils\fixes.py", line 324, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr
  File "C:\Anaconda3_64\lib\site-packages\scipy\sparse\linalg\__init__.py", line 109, in <module>
    from .isolve import *
  File "C:\Anaconda3_64\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\Anaconda3_64\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 7, in <module>
    from . import _iterative
ImportError: DLL load failed: The specified module could not be found.

why? and how to fix it!?

by the way, if in cmd, using  "pip freeze" commond, it shows hmmlearn and the version of it is 0.2.0.
BUT, if using "conda list", no hmmlearn shows!!

**Comment by superbobry** [comment]
Hello, from the traceback this looks like an issue with SciPy installation. Can you try importing `scipy.sparse.linalg`?

> by the way, if in cmd, using "pip freeze" commond, it shows hmmlearn and the version of it is 0.2.0.
BUT, if using "conda list", no hmmlearn shows!!

`conda` and `pip` are different package managers. `conda` installs the packages from [conda-recipes](https://github.com/conda/conda-recipes) which might or might not be related to Python. `pip` on the other hand deals only with Python packages. `hmmlearn` doesn't have a `conda` recipe, so you must've installed it via `pip`. That is why it is present in `pip freeze` and absent in `conda list`.

**Comment by genliu777** [comment]
thanks a lot first!!!
just code "import scipy.sparse.linalg" in pycharm, and get the error:
Traceback (most recent call last):
  File "E:/pycharm/plot_hmm_stock_analysis/hmm_stock_analysis.py", line 18, in <module>
    import scipy.sparse.linalg
  File "C:\Anaconda3_64\lib\site-packages\scipy\sparse\linalg\__init__.py", line 109, in <module>
    from .isolve import *
  File "C:\Anaconda3_64\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\Anaconda3_64\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 7, in <module>
    from . import _iterative
ImportError: DLL load failed: The specified module could not be found.

why? does it mean that scipy not properly set up!? if so, how to fix it? remove scipy and reinstall it again?

**Comment by superbobry** [comment]
Clearly SciPy installation is broken. Try reinstalling, if it doesn't help I suggest to open a SciPy issue and continue the discussion there.

**Comment by genliu777** [comment]
again， THANKS A LOT!!!
it is solved!!!
i try again to reinstall scipy  and numpy which is download from http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy

**Comment by superbobry** [comment]
Glad to help. Closing the issue.

**Comment by dhoksrushti** [comment]
HI ,

I am facing the issue in Win 10 where I have manually downloaded scipy-0.19.1-cp35-cp35m-win_amd64.whl and reinstalled it. Still the issue persist

 import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Srushti\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\__init__.py", line 134, in <module>
    from .base import clone
  File "C:\Users\Srushti\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\base.py", line 12, in <module>
    from .utils.fixes import signature
  File "C:\Users\Srushti\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "C:\Users\Srushti\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\utils\validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "C:\Users\Srushti\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\utils\fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "C:\Users\Srushti\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\linalg\__init__.py", line 113, in <module>
    from .isolve import *
  File "C:\Users\Srushti\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\Users\Srushti\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 7, in <module>
    from . import _iterative
ImportError: DLL load failed: The specified module could not be found.


Please suggest

**Comment by Patrikejane** [comment]
@dhoksrushti is you error  solved? if solved is it from above mention fix?

**Comment by vaishvel** [comment]
@dhoksrushti Facing the same issue. Any solutions?

**Comment by quancq** [comment]
@dhoksrushti . I am facing the same issue (my computer is Win7 64bit and Python 3.6) and solution is install numpy + MKL from http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy. And this article i find solution https://stackoverflow.com/questions/30766274/error-importing-scikit-learn-modules

**Comment by yan-zhao** [comment]
I'm on windows 10 python 3.5 64 bits. The standard numpy installation has no MKL in it. quancq's solution solved my problem.

**Comment by Patrikejane** [comment]
according to this article   https://stackoverflow.com/questions/28568070/filename-whl-is-not-supported-wheel-on-this-platform
`>>import pip`
`>>print(pip.pep425tags.get_supported())`
using above code lines we can see what are the whl version(cp, OS) compatibale with our installed python version. then http://www.lfd.uci.edu/~gohlke/pythonlibs/  from here u can get the correct extention numpy,scipy ....... and install. this worked for me.

**Comment by animeshsingh04** [comment]
C:\Users\Student\PycharmProjects\project\venv\Scripts\python.exe C:/Users/Student/PycharmProjects/project/shmm_main.py
Traceback (most recent call last):
  File "C:/Users/Student/PycharmProjects/project/shmm_main.py", line 6, in <module>
    from hmmlearn import hmm
ModuleNotFoundError: No module named 'hmmlearn'

but when I'm trying to download hmmlearn package it showing this error

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tool

Collecting hmmlearn
  Using cached https://files.pythonhosted.org/packages/dd/9e/6822b0cb04660f897cffb0ef39020423b342548803015f9b6e7dffeed2a8/hmmlearn-0.2.0.tar.gz
Installing collected packages: hmmlearn
  Running setup.py install for hmmlearn: started
    Running setup.py install for hmmlearn: finished with status 'error'
    Complete output from command C:\Users\Student\PycharmProjects\project\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Student\\AppData\\Local\\Temp\\pycharm-packaging\\hmmlearn\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Student\AppData\Local\Temp\pip-evb0i94l-record\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Student\PycharmProjects\project\venv\include\site\python3.6\hmmlearn:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\hmmlearn
    copying hmmlearn\base.py -> build\lib.win32-3.6\hmmlearn
    copying hmmlearn\hmm.py -> build\lib.win32-3.6\hmmlearn
    copying hmmlearn\utils.py -> build\lib.win32-3.6\hmmlearn
    copying hmmlearn\__init__.py -> build\lib.win32-3.6\hmmlearn
    creating build\lib.win32-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_base.py -> build\lib.win32-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_gaussian_hmm.py -> build\lib.win32-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_gmm_hmm.py -> build\lib.win32-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_multinomial_hmm.py -> build\lib.win32-3.6\hmmlearn\tests
    copying hmmlearn\tests\test_utils.py -> build\lib.win32-3.6\hmmlearn\tests
    copying hmmlearn\tests\__init__.py -> build\lib.win32-3.6\hmmlearn\tests
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building 'hmmlearn._hmmc' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    
    ----------------------------------------

Command "C:\Users\Student\PycharmProjects\project\venv\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Student\\AppData\\Local\\Temp\\pycharm-packaging\\hmmlearn\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Student\AppData\Local\Temp\pip-evb0i94l-record\install-record.txt --single-version-externally-managed --compile --install-headers C:\Users\Student\PycharmProjects\project\venv\include\site\python3.6\hmmlearn" failed with error code 1 in C:\Users\Student\AppData\Local\Temp\pycharm-packaging\hmmlearn\
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

I updated pip also but still showing same issue

**Comment by dmopalmer** [comment]
To add another datapoint.  I just installed a fresh version of minconda (me only, don't add to path, using anaconda prompt, on Windows 7 64bit).  I get the error.
```
(streak) C:\Users\150772>conda activate scipytest
(scipytest) C:\Users\150772>python
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  5 2016, 14:53:07) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.stats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\150772\AppData\Local\Continuum\miniconda3\envs\scipytest\lib\site-packages\scipy\stats\__init__.py", li
ne 348, in <module>
    from .stats import *
  File "C:\Users\150772\AppData\Local\Continuum\miniconda3\envs\scipytest\lib\site-packages\scipy\stats\stats.py", line
175, in <module>
    import scipy.special as special
  File "C:\Users\150772\AppData\Local\Continuum\miniconda3\envs\scipytest\lib\site-packages\scipy\special\__init__.py",
line 640, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.
>>>
```

The setup:
```
(streak) C:\Users\150772>conda create -n scipytest python=3.4 scipy
Solving environment: done

## Package Plan ##

  environment location: C:\Users\150772\AppData\Local\Continuum\miniconda3\envs\scipytest

  added / updated specs:
    - python=3.4
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-9.0.1                  |           py34_1         1.7 MB
    vc-10                      |                0          702 B
    wheel-0.29.0               |           py34_0         123 KB
    python-3.4.5               |                0        22.9 MB
    setuptools-27.2.0          |           py34_1         762 KB
    ------------------------------------------------------------
                                           Total:        25.5 MB

The following NEW packages will be INSTALLED:

    intel-openmp:   2018.0.0-8
    mkl:            2017.0.4-h6d528fc_0
    numpy:          1.11.3-py34_0
    pip:            9.0.1-py34_1
    python:         3.4.5-0
    scipy:          0.19.1-np111py34_0
    setuptools:     27.2.0-py34_1
    vc:             10-0
    vs2010_runtime: 10.00.40219.1-2
    wheel:          0.29.0-py34_0

Proceed ([y]/n)?


Downloading and Extracting Packages
pip 9.0.1###################################################################################################### | 100%
vc 10########################################################################################################## | 100%
wheel 0.29.0################################################################################################### | 100%
python 3.4.5################################################################################################### | 100%
setuptools 27.2.0############################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate scipytest
#
# To deactivate an active environment, use
#
#     $ conda deactivate

```
The info
```
(scipytest) C:\Users\150772>conda info

     active environment : scipytest
    active env location : C:\Users\150772\AppData\Local\Continuum\miniconda3\envs\scipytest
            shell level : 2
       user config file : C:\Users\150772\.condarc
 populated config files :
          conda version : 4.5.3
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : C:\Users\150772\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\150772\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\150772\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\150772\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\150772\AppData\Local\conda\conda\envs
                          C:\Users\150772\.conda\envs
               platform : win-64
             user-agent : conda/4.5.3 requests/2.18.4 CPython/3.6.5 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False

```

**Comment by Sushanti99** [comment]
In case anybody is still facing similar issues:

I kept facing the same issue and uninstalling and installing scipy did not help.
Turns out I had to close an active script that was running in the background and then uninstall and reinstall scipy using pip.
This worked for me.

**Comment by ayush9pandey** [comment]
Active scripts/jupyter notebook kernels cause these errors as well, as pointed out, especially when a new package is installed you should restart all such scripts first.

**Comment by Yoman3597** [comment]
Traceback (most recent call last):
  File "C:\Users\DAKSHESH\Desktop\CHECK.PY", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\sklearn\__init__.py", line 74, in <module>
    from .base import clone
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\sklearn\base.py", line 20, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\sklearn\utils\__init__.py", line 25, in <module>
    from .fixes import np_version
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 291, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .isolve import *
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 10, in <module>
    from . import _iterative
ImportError: DLL load failed: The specified module could not be found.



HOW TO SOLVE ????????????????

**Comment by Yoman3597** [comment]
from sklearn.model_selection import train_test_split


Traceback (most recent call last):
  File "C:\Users\DAKSHESH\Desktop\CHECK.PY", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\sklearn\__init__.py", line 74, in <module>
    from .base import clone
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\sklearn\base.py", line 20, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\sklearn\utils\__init__.py", line 25, in <module>
    from .fixes import np_version
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 291, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .isolve import *
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\Users\DAKSHESH\Anaconda3\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 10, in <module>
    from . import _iterative
ImportError: DLL load failed: The specified module could not be found




PLEASE SOLVE IT...........................

**Comment by Ayush-Porwal** [comment]
I am trying to import sklearn using import sklearn but I am getting the following error. (Window10, python 3.7)

Please help asap, need a working installation of anaconda3 for my project.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\__init__.py", line 76, in <module>
    from .base import clone
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py", line 16, in <module>
    from .utils import _IS_32BIT
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\__init__.py", line 20, in <module>
    from .validation import (as_float_array,
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 21, in <module>
    from .fixes import _object_dtype_isnan
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 18, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 116, in <module>
    from .eigen import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: The specified procedure could not be found.
